name: Test

on:
  pull_request:
    branches: [ master ]

env:
  SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.17'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: npm ci
    - run: git submodule update --init --recursive
    - run: npm test
