name: Test

on:
  pull_request:
    branches: [ master ]

env:
  SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.17'
    - run: npm ci
    - run: |
        git config --global user.name 'AmbNum Bot'
        git config --global user.email 'ambnum.bot@disinfo.quaidorsay.fr'
    - run: npm test
